
version: "3.8"

services:
  ncwms:
    container_name: ncwms
    build: .
    image: ${IMAGE_URI}
    restart: always
    ports:
      - ${PORT}:8080
    volumes: 
      - ./config/context.xml:/usr/local/tomcat/conf/context.xml
      - ./config/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ${CONFIG_VOLUME}:/usr/local/tomcat/.ncWMS2
      - ${DATASETS_VOLUME}:/opt/tomcat/EACW_DATA